[package]
name = "unimock"
version = "0.4.8"
authors = ["Audun Halland <audun.halland@pm.me>"]
edition = "2021"
rust-version = "1.65"
license = "MIT"
description = "A versatile and developer-friendly trait mocking library"
repository = "https://github.com/audunhalland/unimock/"
keywords = ["mocking", "mock", "testing", "test"]
categories = ["development-tools", "development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["pretty-print"]
pretty-print = ["dep:pretty_assertions"]
nightly-tests = []

[dependencies]
unimock_macros = { path = "unimock_macros", version = "0.4.8" }
once_cell = "1"
pretty_assertions = { version = "1.3", optional = true }

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

[workspace]
members = ["unimock_macros"]
