[package]
name = "unimock"
version = "0.4.0-alpha.3"
authors = ["Audun Halland <audun.halland@pm.me>"]
edition = "2021"
rust-version = "1.65"
license = "MIT"
description = "Unimock type for working with multiple trait bounds"
repository = "https://github.com/audunhalland/unimock/"
keywords = ["test", "mock"]
categories = ["development-tools", "development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
nightly-tests = []

[dependencies]
unimock_macros = { path = "unimock_macros", version = "0.4.0-alpha.3" }
lazycell = "1"

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

[workspace]
members = ["unimock_macros"]
