[package]
name = "unimock"
version = "0.5.0-alpha.0"
authors = ["Audun Halland <audun.halland@pm.me>"]
edition = "2021"
rust-version = "1.65"
license = "MIT"
description = "A versatile and developer-friendly trait mocking library"
repository = "https://github.com/audunhalland/unimock/"
keywords = ["mocking", "mock", "testing", "test"]
categories = ["development-tools", "development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["pretty-print", "std"]
pretty-print = ["dep:pretty_assertions"]
nightly-tests = []
std = []
unstable-doc-cfg = []

[dependencies]
unimock_macros = { path = "unimock_macros", version = "0.5.0-alpha.0" }
once_cell = "1.17"
spin = "0.9"
pretty_assertions = { version = "1.3", optional = true }
doc-cfg = "0.1"

[dev-dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
features = ["unstable-doc-cfg"]

[workspace]
members = ["unimock_macros"]
