name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-hack
      - name: Test
        run: cargo hack \
          --feature-powerset \
          --exclude-features default,nightly-tests,unstable-doc-cfg \
          test --all
      - name: Doctest
        run: cargo test --doc
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

  test-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Test nightly features
        run: cargo test --all --all-features
